# Generated by Django 4.2.6 on 2023-11-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
