# Generated by Django 4.2.6 on 2023-12-01 14:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_cartitem_cart_cartitem_user_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
