# Generated by Django 4.2.6 on 2023-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
