# Generated by Django 4.2.6 on 2023-12-27 17:15

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_cartitem_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'), editable=False, populate_from=models.CharField(blank=True, max_length=250, null=True), unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
