# Generated by Django 4.2.6 on 2023-12-27 17:18

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_slug_alter_product_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'), editable=False, populate_from='product_title', unique=True),
        ),
    ]
